## Introduction to the extended version of DiCE (Diverse Counterfactual Explanations)

[Mothilal et al. (2020)](https://dl.acm.org/doi/10.1145/3351095.3372850) introduce their method of generating counterfactual explanations considering _feasibility_, and _diversity_. [Guidotti and Ruggieri (2021)](https://link.springer.com/chapter/10.1007/978-3-030-88942-5_28), claim counterfactual explanations to be robust they should be similar for similar instances when they explain. In this study, in a search to improve the quality and reliability of the counterfactual explanations _robustness_ is found to be helpful and it also introduced in the optimization function.

DiCE-Extended is built upon the [DiCE (Diverse Counterfactual Explanations)](https://github.com/interpretml/DiCE) [(Mothilal et al. 2020)](https://dl.acm.org/doi/10.1145/3351095.3372850) framework by introducing a robustness term in the optimization function.

## Manipulated Optimization Function

The core enhancement in DiCE-Extended is the manipulated optimization function, designed to balance proximity, diversity, and feasibility of counterfactuals. The function is formulated as:

<a id="equation-1"></a>
\begin{equation}
\tag{1}
C(x) = \underset{c_1, ..., c_k}{\text{arg min}}
\frac{1}{2} \sum_{i=1}^{k} yloss(f(c_i), y) +
\frac{\lambda_1}{k} \sum_{i=1}^{k} dist(c_i, x) -
\lambda_2 \cdot dpp\_diversity(c_1, ..., c_k) -
\frac{\lambda_3}{k} \sum_{i=1}^{k} robustness(c_i, c_i')
\end{equation}

- **Proximity Loss**: The first term that averages the distance between generated counterfactuals and the original input ensure the counterfactuals to be as close as possible to the original input.
- **Diversity Loss**: Diversity of the counterfactual explanations is aquired by determinental point process of which loss is represented by the second term and it ensures that _k_ number of counterfactual explanations are generated.
- **Robustness Loss**: [Guidotti (2024)](https://link.springer.com/article/10.1007/s10618-022-00831-6) defines robustness as necessity of similar instances being explained by similar counterfactual explanations such that if $b(x_1)=b(x_2)=y$ then an explainer $f$ should generate counterfactuals $c_1$ and $c_2$ that are similar and can explain $x_1$ and $x_2$. The robustness term that is based on [Dice-Sørensen Coefficient](https://en.wikipedia.org/wiki/Dice-S%C3%B8rensen_coefficient), is adopted from [Bonasera and Carrizosa (2024)](
https://doi.org/10.48550/arXiv.2407.00843).

\begin{equation}
\tag{2}
Robustness(c_i, c_i') = \frac{2 * \lvert c_i \cap c_i' \rvert}{\lvert c_i \rvert + \lvert c_i' \rvert}
\end{equation}


By adjusting the weights $\lambda_1$, $\lambda_2$, $\lambda_3$ counterfactual explanations can be customised by specific needs.

## Metrics and Sensitivity Analysis for Dice Extended


### 1. Robustness Metrics

#### Dice-Sørensen Coefficient

To evaluate robustness, the Dice-Sørensen coefficient measures the similarity between counterfactuals c1 and
c2 generated for similar input instances x1 and x2:

\begin{equation}
\tag{3}
Robustness(c_1, c_2) = \frac{2 * \lvert c_1 \cap c_2 \rvert}{\lvert c_1 \rvert + \lvert c_2 \rvert}
\end{equation}

where:
- $ c_1 $ and $ c_2 $ are binary vectors,
- $ \lvert c_1 \cap c_2 \rvert $: The number of shared (overlapping) features between c1 and c2,
- $ \lvert c_1 \rvert $ and $ \lvert c_2 \rvert $: The total number of features in each counterfactual.

#### Input Perturbation and Stability

Stability under input perturbation measures the solution variance when slight perturbations are introduced
to the input instance. The procedure includes the following steps:

1) **Apply Gaussian Noise:** Perturb the input $x$ by adding Gaussian noise $\delta$ to create perturbed inputs
$x'$:

\begin{equation}
\tag{4}
x' = x + \delta, \quad \delta \sim \mathcal{N}(0, \sigma^2)
\end{equation}

where $\sigma$ is the standard deviation of the noise (e.g., $\sigma = 0.01$).

2) **Generate Counterfactuals:** Generate counterfactual explanations $c_i$ for the original input $x$ and $c_i'$ for the perturbed input $x'$.

3) **Measure Stability:** Compare counterfactuals using a distance metric, such as the Euclidean distance:

\begin{equation}
\tag{5}
Stability = \frac{1}{n} \sum_{i=1}^{n} dist(c_i, c_i')
\end{equation}

where:

\begin{equation}
\tag{6}
dist(c_i, c_i') = \sqrt{\sum_{j=1}^{d} (c_{ij} - c_{ij}')^2}
\end{equation}

$n$ is the total number of input instances, $c_i$ is the counterfactual for the original input, and $c_i'$ is the counterfactual for the perturbed input.

### 2. Counterfactual Quality Measures

#### Fidelity

Fidelity measures how often generated counterfactuals successfully change the model’s prediction:

\begin{equation}
\tag{7}
Fidelity = \frac{\sum_{i=1}^{n} \mathbf{1}(f(c_i) = y_{desired})}{n}
\end{equation}

where:

- $f$: Prediction model,
- $c_i$: Counterfactual instance,
- $y_{desired}$: Target output class,
- $n$: Total number of counterfactuals.

#### Proximity

Proximity measures the average distance between counterfactuals $c_i$ and the original inputs $x_i$:

\begin{equation}
\tag{8}
Proximity = \frac{1}{n} \sum_{i=1}^{n} dist(x_i, c_i)
\end{equation}

The Manhattan distance can be used for simplicity:

\begin{equation}
\tag{9}
dist(x_i, c_i) = \sum_{j=1}^{d} \lvert x_{ij} - c_{ij} \rvert
\end{equation}

#### Diversity

Diversity measures how dissimilar the counterfactuals $c_1, c_2, c_3,\ldots,c_k$ are among themselves:

\begin{equation}
\tag{10}
Diversity = \frac{1}{k(k-1)}\sum_{i_1}^{k}\sum_{j \neq i}^{} dist(c_i, c_j)
\end{equation}

where $k$ is the number of counterfactuals.

### 3. Sensitivity Analysis

#### Objective Function with Weights

The modified loss function in DiCE-Extended is defined as in the [equation 1](#equation-1) where:

- $yloss(f(c_i), y)$: Prediction loss for counterfactual instance $c_i$ relative to the desired outcome $y$,
- $dist(c_i, x)$: Distance metric (e.g., Euclidean or Manhattan) between the counterfactual c_i and the original input $x$,
- $dpp_diversity(c_1,\ldots,c_k)$: Diversity loss term based on Determinantal Point Process (DPP),
- $Robustness(c_i,c_i')$: Robustness loss measuring similarity of counterfactuals under perturbations.

  The weights $\lambda_1, \lambda_2, \lambda_3$ control the balance between proximity, diversity, and robustness, respectively.

#### Sensitivity Analysis

To perform sensitivity analysis:

1) Vary the weights $\lambda_1, \lambda_2, \lambda_3$ systematically while ensuring:

\begin{equation}
\tag{11}
\lambda_1 + \lambda_2 + \lambda_3 = 1 (for normalization).
\end{equation}

2) Track the changes in the following metrics:

\begin{equation}
\tag{12}
P(\lambda_1, \lambda_2, \lambda_3) = Proximity,
\end{equation}

\begin{equation}
\tag{13}
D(\lambda_1, \lambda_2, \lambda_3) = Diversity,
\end{equation}

\begin{equation}
\tag{14}
R(\lambda_1, \lambda_2, \lambda_3) = Robustness,
\end{equation}

3) Measure the relationship between these metrics and the weights.

In [1]:
import sys
dice_path = "/Users/volk/Documents/bau24-25/thesis/repos/DiCE-X"
sys.path.insert(0, dice_path)

In [2]:
import numpy as np
import timeit
import random
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

from torch.utils.data import DataLoader

import dice_ml_x
from dice_ml_x.utils import helpers
from dice_ml_x.utils import neuralnetworks
from dice_ml_x import DiceX

In [3]:
%load_ext autoreload
%autoreload 2

In [27]:
datasets = ["compas", "adult-income", "german-credit-risk", "lending-club"]
from dice_ml_x.utils import helpers
    

df_lending = helpers.load_lending_club_dataset()
cat_columns = df_lending.columns.difference(list(df_lending.select_dtypes(include=[np.number])))
df_lending['stratify_column'] = df_lending[cat_columns].astype(str).agg('_'.join, axis=1)



# Filter the target variable to match the filtered dataframe
target = df_lending["loan_status"]

train_dataset, test_dataset, y_train, y_test = train_test_split(df_lending,
                                                                target,
                                                                test_size=0.2,
                                                                random_state=42,
                                                                stratify=target)
x_train = train_dataset.drop(columns=['stratify_column'])
x_test = test_dataset.drop(columns=['stratify_column'])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

transformations = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, cat_columns)])

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
clf = Pipeline(steps=[('preprocessor', transformations),
                      ('classifier', RandomForestClassifier())])
model = clf.fit(x_train, y_train)

In [39]:
df_lending = helpers.load_lending_club_dataset()
numerical = df_lending.select_dtypes(include=[np.number]).columns

categorical = df_lending.columns.difference(numerical).difference(['loan_status'])
import torch

from torch.utils.data import random_split, DataLoader
target = df_lending['loan_status']
features = df_lending.drop(columns=['loan_status'])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

transformations = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical)])

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
clf = Pipeline(steps=[('preprocessor', transformations)])

transformed_data = clf.fit_transform(features)
# Example dataset
dataset = torch.utils.data.TensorDataset(torch.tensor(transformed_data.toarray(), dtype=torch.float32),
                                         torch.tensor(df_lending['loan_status'].values))

# Split sizes
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size

# Split
train_dataset, test_dataset = random_split(dataset, [train_size, test_size])

# Create DataLoaders
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

In [44]:
dummy_input, dummy_label = next(iter(train_loader))
in_features = dummy_input.shape[1]
pyt_model = neuralnetworks.PYTModel(in_features)
trainer = pyt_model.train(train_dataloader=train_loader, test_dataloader=test_loader)

In [ ]:
d = dice_ml_x.Data(dataframe=train_dataset, continuous_features=["age", "juv_misd_count", "priors_count"], outcome_name='twoyearrecid')

In [15]:
import pickle

with open("benchmarking_results.pkl", "wb") as f:
    pickle.dump(benchmarking.results, f)

In [11]:
benchmarking.results
m = dice_ml_x.Model(model=benchmarking.results['compas-recidivism']['PYT'], backend='PYT', func="ohe-min-max")

In [14]:
dummy_compas = helpers.load_compas_dataset()
c_target = dummy_compas['twoyearrecid']
c_train_dataset, c_test_dataset, c_y_train, c_y_test = train_test_split(dummy_compas, c_target, test_size=0.2,
                                                                        random_state=0,
                                                                        stratify=c_target)
compas_train_dataloader
m.model.model(c_test_dataset)

TypeError: linear(): argument 'input' (position 1) must be Tensor, not DataFrame

In [94]:

lending_df = helpers.load_lending_club_dataset()
target = lending_df['loan_status']

categorical_columns = lending_df.columns.difference(list(lending_df.select_dtypes(include=[np.number])))
lending_df['composite_stratify'] = lending_df[categorical_columns].astype(str).agg('_'.join, axis=1)

# Ensure each class in composite_stratify has at least two members
value_counts = lending_df['composite_stratify'].value_counts()
valid_classes = value_counts[value_counts >= 2].index
lending_df = lending_df[lending_df['composite_stratify'].isin(valid_classes)]

# Filter the target variable to match the filtered dataframe
target = target[lending_df.index]

# Split the dataset, ensuring all categories are present in both splits
train_dataset, test_dataset, y_train, y_test = train_test_split(lending_df, target, test_size=0.2, random_state=42, stratify=lending_df['composite_stratify'])

# Drop the composite column after splitting
train_df = train_dataset.drop(columns=['composite_stratify'])
test_df = test_dataset.drop(columns=['composite_stratify'])

train_sub_unique = train_dataset['sub_grade'].unique().tolist()
test_sub_unique = test_dataset['sub_grade'].unique().tolist()
print(set(train_sub_unique) - set(test_sub_unique))

ValueError: The test_size = 305 should be greater or equal to the number of classes = 682

In [63]:
import pickle
with open("benchmarking_results_fin.pkl", "wb") as f:
    pickle.dump(benchmarking.results, f)

In [12]:
benchmarking.results

{'compas-recidivism': {'sklearn': {'accuracy': 0.6197183098591549,
   'cfs': {'gaussian':     sex   age  juv_misd_count  priors_count        age_cat       race  \
    0  Male  49.0             0.0          10.0  Greaterthan45  Caucasian
    0  Male  49.0             0.0           6.0  Greaterthan45  Caucasian
    0  Male  53.0             0.0          10.0  Greaterthan45  Caucasian
    0  Male  45.0             0.0          13.0  Greaterthan45  Caucasian

      c_charge_degree  twoyearrecid
    0               M             0
    0               F             0
    0               F             0
    0               F             0  ,
    'random':     sex   age  juv_misd_count  priors_count        age_cat              race  \
    0  Male  47.2             0.0          10.0  Greaterthan45         Caucasian
    0  Male  46.0             0.0          10.0  Greaterthan45         Caucasian
    0  Male  19.0             0.0           0.0  Greaterthan45         Caucasian
    0  Male  19.0             0.0           0.0  Greaterthan45  African-American

      c_charge_degree  twoyearrecid
    0               F             0
    0               F             0
    0               F             0
    0               M             0  ,
    'spherical':       sex   age  juv_misd_count  priors_count        age_cat  \
    0    Male  19.0             0.0           0.0  Greaterthan45
    0    Male  19.0             0.0           0.0  Greaterthan45
    0  Female  19.0             0.0           0.0  Greaterthan45
    0  Female  19.0             0.0           0.0          25-45

                   race c_charge_degree  twoyearrecid
    0  African-American               M             0
    0         Caucasian               F             0
    0  African-American               F             0
    0  African-American               F             0  },
   'input_instance': {'gaussian':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'random':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'spherical':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  },
   'time': {'gaussian': 14698.590993881226,
    'random': 421216.83406829834,
    'spherical': 443332.5707912445},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['age_cat', 'c_charge_degree', 'race', 'sex'], dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.5,
   'cfs': {'gaussian':     sex   age  juv_misd_count  priors_count        age_cat              race  \
    0  Male  19.0            13.0          10.5          25-45  African-American
    1  Male  19.0             0.1          17.3  Greaterthan45  African-American
    2  Male  36.5             6.3          21.7          25-45  African-American
    3  Male  29.4             0.0          28.4  Greaterthan45  African-American

      c_charge_degree  twoyearrecid
    0               M         0.726
    1               M         0.704
    2               M         0.727
    3               M         0.720  ,
    'random':     sex   age  juv_misd_count  priors_count        age_cat              race  \
    0  Male  19.0            13.0          10.0          25-45  African-American
    1  Male  19.0             0.0          17.4  Greaterthan45  African-American
    2  Male  38.2             7.5          21.0          25-45  African-American
    3  Male  30.5             0.0          29.0  Greaterthan45  African-American

      c_charge_degree  twoyearrecid
    0               M         0.724
    1               M         0.705
    2               M         0.720
    3               M         0.719  ,
    'spherical':     sex   age  juv_misd_count  priors_count        age_cat              race  \
    0  Male  19.0            13.0          10.3          25-45  African-American
    1  Male  19.0             0.0          17.2  Greaterthan45  African-American
    2  Male  36.7             6.3          21.7          25-45  African-American
    3  Male  30.5             0.0          28.7  Greaterthan45  African-American

      c_charge_degree  twoyearrecid
    0               M         0.725
    1               M         0.704
    2               M         0.726
    3               M         0.718  },
   'input_instance': {'gaussian':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'random':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'spherical':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  },
   'time': {'gaussian': 86506.19506835938,
    'random': 153236.79423332214,
    'spherical': 217953.95302772522},
   'state_dict': OrderedDict([('0.weight',
                 tensor([[-0.1051, -0.3494, -0.4873,  0.0416,  0.2532,  0.1892, -0.2239, -0.0349,
                          -0.1847,  0.1007,  0.1725,  0.2200],
                         [-0.1218, -0.2298, -0.0360,  0.0232,  0.2375,  0.0095,  0.2349, -0.2795,
                           0.1974,  0.1697,  0.2497, -0.1245],
                         [-0.1566, -0.1236,  0.3135, -0.2959,  0.1691,  0.3980,  0.1996,  0.0136,
                           0.3339, -0.2390, -0.2863,  0.3601],
                         [ 0.0074,  0.1983, -0.6856,  0.1462,  0.1990,  0.0435, -0.0831, -0.1060,
                           0.1605,  0.3216, -0.1144,  0.1348],
                         [-0.4333,  0.1983,  0.0094,  0.1735,  0.2773,  0.0663, -0.0240, -0.0548,
                          -0.0562, -0.2624, -0.2262, -0.1391],
                         [ 0.1143, -0.1374, -0.6093, -0.0323, -0.0063,  0.0139, -0.0061, -0.3241,
                          -0.0885,  0.2170,  0.0014,  0.2364],
                         [-0.0819, -0.0420, -0.0058,  0.1839, -0.2333, -0.2080, -0.1577, -0.1092,
                           0.0063,  0.2269,  0.0846,  0.0269],
                         [-0.4090, -0.0925,  0.4518,  0.2108,  0.2009,  0.0635,  0.1647, -0.0867,
                           0.2046,  0.2575, -0.1489, -0.0068],
                         [-0.2262, -0.0033,  0.0237, -0.1483, -0.1301,  0.4026,  0.0799,  0.1559,
                           0.0607, -0.3220, -0.3493,  0.1315],
                         [-0.0726,  0.1895,  0.0494, -0.3202,  0.3405,  0.0492, -0.0987, -0.3931,
                          -0.0884, -0.2370, -0.0104,  0.0252],
                         [ 0.2488, -0.0401,  0.3411, -0.0302, -0.3016, -0.3084,  0.0412, -0.3048,
                           0.1848, -0.1366, -0.2910, -0.0726],
                         [ 0.0566, -0.1423,  0.0405,  0.1550, -0.1259, -0.5130,  0.0308, -0.3829,
                          -0.4881, -0.0771,  0.3246, -0.1069],
                         [ 0.0981,  0.1329, -0.3569,  0.1698, -0.2746, -0.2221,  0.0730, -0.0034,
                           0.2624, -0.4653,  0.2240, -0.0476],
                         [ 0.3061, -0.1378, -0.5061,  0.1252,  0.1206,  0.2052, -0.0436,  0.1134,
                          -0.1738, -0.0169,  0.3747,  0.1940],
                         [-0.1754, -0.1362, -0.6758,  0.1947, -0.3097,  0.2348,  0.1043, -0.1583,
                           0.2391,  0.1223, -0.1207, -0.2419],
                         [-0.0254,  0.1629,  0.0213, -0.2125, -0.2669,  0.0392, -0.2126, -0.0298,
                           0.1148, -0.2408, -0.0337, -0.1930],
                         [ 0.2025, -0.0729, -0.5641,  0.1939,  0.1700, -0.0493,  0.1895,  0.0026,
                           0.0040,  0.2326,  0.0948, -0.0747],
                         [-0.5354,  0.0698,  0.3339,  0.0252, -0.0839,  0.0515, -0.1657, -0.1451,
                          -0.1090,  0.0112,  0.1878,  0.2093],
                         [-0.2706, -0.1049,  0.2695,  0.0958,  0.1556,  0.1253,  0.1649, -0.0986,
                           0.1897,  0.1084,  0.2352,  0.2390],
                         [-0.0380, -0.3028, -0.6034,  0.0702,  0.2445, -0.1002, -0.2397,  0.1349,
                           0.0406, -0.1316,  0.2314, -0.2097]])),
                ('0.bias',
                 tensor([ 0.0227,  0.1288, -0.0678,  0.2304,  0.2331,  0.2229, -0.0334,  0.1954,
                         -0.0776, -0.2170,  0.0429,  0.2527, -0.0502,  0.1888, -0.2041,  0.0243,
                          0.1707,  0.1278, -0.0530,  0.2730])),
                ('2.weight',
                 tensor([[-0.2155, -0.0765,  0.2155, -0.1583,  0.1515, -0.1292,  0.0640,  0.3743,
                           0.3574,  0.1005, -0.3064,  0.3691, -0.3822, -0.2314, -0.3564, -0.0667,
                          -0.2644,  0.4954,  0.3955, -0.2667]])),
                ('2.bias', tensor([-0.0033]))]),
   'model': Sequential(
     (0): Linear(in_features=12, out_features=20, bias=True)
     (1): ReLU()
     (2): Linear(in_features=20, out_features=1, bias=True)
     (3): Sigmoid()
   )}}}

In [13]:
from dice_ml_x.benchmarking import Benchmarking
datasets = ["compas-recidivism", "adult-income", "lending-club", "german-credit"]
datasets = ["compas-recidivism", "adult-income"]
backends = ["sklearn", "PYT", "TF2"]
methods = ['gaussian', 'random', 'spherical']
benchmarking = Benchmarking(datasets=datasets,
                            backends=backends,
                            perturbation_methods=methods)
benchmarking.load_and_train(batch_size=16)
from datetime import datetime
import pickle
current_time = datetime.now()
formatted_timestamp = current_time.strftime("%d_%m_%Y-%H_%M_%S")
with open(f"benchmarking_results_{formatted_timestamp}.pkl", "wb") as res_file:
    pickle.dump(benchmarking.results, res_file)

Benchmarking:   0%|          | 0/6 [00:00<?, ?it/s]

the dataset is : compas-recidivism, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [00:15<00:00, 15.71s/it]

the dataset is : compas-recidivism, the backend is : sklearn, the method is random

100%|██████████| 1/1 [00:59<00:00, 59.52s/it]

the dataset is : compas-recidivism, the backend is : sklearn, the method is spherical

100%|██████████| 1/1 [03:21<00:00, 201.18s/it]
Benchmarking:  17%|█▋        | 1/6 [04:36<23:03, 276.64s/it, dataset=compas-recidivism, backend=sklearn, method=spherical]

the dataset is : compas-recidivism, the backend is : PYT, the method is gaussian

WARNING:root: MAD for feature juv_misd_count is 0, so replacing it with 1.0 to avoid error.
100%|██████████| 1/1 [00:49<00:00, 49.47s/it]

Diverse Counterfactuals found! total time taken: 00 min 49 sec
the dataset is : compas-recidivism, the backend is : PYT, the method is random

WARNING:root: MAD for feature juv_misd_count is 0, so replacing it with 1.0 to avoid error.
100%|██████████| 1/1 [02:11<00:00, 131.80s/it]

Diverse Counterfactuals found! total time taken: 02 min 11 sec
the dataset is : compas-recidivism, the backend is : PYT, the method is spherical

WARNING:root: MAD for feature juv_misd_count is 0, so replacing it with 1.0 to avoid error.
100%|██████████| 1/1 [01:04<00:00, 64.42s/it]
Benchmarking:  33%|███▎      | 2/6 [08:43<17:16, 259.15s/it, dataset=compas-recidivism, backend=PYT, method=spherical]

Diverse Counterfactuals found! total time taken: 01 min 04 sec

WARNING:root: MAD for feature juv_misd_count is 0, so replacing it with 1.0 to avoid error.

the dataset is : compas-recidivism, the backend is : TF2, the method is gaussian

WARNING:root: MAD for feature juv_misd_count is 0, so replacing it with 1.0 to avoid error.

Diverse Counterfactuals found! total time taken: 01 min 54 sec
the dataset is : compas-recidivism, the backend is : TF2, the method is random

WARNING:root: MAD for feature juv_misd_count is 0, so replacing it with 1.0 to avoid error.

Diverse Counterfactuals found! total time taken: 03 min 03 sec
the dataset is : compas-recidivism, the backend is : TF2, the method is spherical

Benchmarking:  50%|█████     | 3/6 [16:51<18:11, 363.84s/it, dataset=compas-recidivism, backend=TF2, method=spherical]

Diverse Counterfactuals found! total time taken: 03 min 08 sec
the dataset is : adult-income, the backend is : sklearn, the method is gaussian

100%|██████████| 1/1 [00:43<00:00, 43.12s/it]

the dataset is : adult-income, the backend is : sklearn, the method is random

100%|██████████| 1/1 [07:05<00:00, 425.46s/it]

the dataset is : adult-income, the backend is : sklearn, the method is spherical

100%|██████████| 1/1 [40:27<00:00, 2427.87s/it]
Benchmarking:  67%|██████▋   | 4/6 [1:05:11<45:29, 1364.83s/it, dataset=adult-income, backend=sklearn, method=spherical]

the dataset is : adult-income, the backend is : PYT, the method is gaussian

100%|██████████| 1/1 [01:35<00:00, 95.81s/it]

Diverse Counterfactuals found! total time taken: 01 min 35 sec
the dataset is : adult-income, the backend is : PYT, the method is random

100%|██████████| 1/1 [03:20<00:00, 200.36s/it]

Diverse Counterfactuals found! total time taken: 03 min 20 sec
the dataset is : adult-income, the backend is : PYT, the method is spherical

100%|██████████| 1/1 [01:09<00:00, 69.65s/it]
Benchmarking:  83%|████████▎ | 5/6 [1:11:23<16:46, 1006.95s/it, dataset=adult-income, backend=PYT, method=spherical]

Diverse Counterfactuals found! total time taken: 01 min 09 sec
the dataset is : adult-income, the backend is : TF2, the method is gaussian
Diverse Counterfactuals found! total time taken: 02 min 05 sec
the dataset is : adult-income, the backend is : TF2, the method is random
Diverse Counterfactuals found! total time taken: 04 min 25 sec
the dataset is : adult-income, the backend is : TF2, the method is spherical

Benchmarking: 100%|██████████| 6/6 [1:22:20<00:00, 823.34s/it, dataset=adult-income, backend=TF2, method=spherical]

Diverse Counterfactuals found! total time taken: 04 min 17 sec

In [15]:
from dice_ml_x.utils import helpers
a = helpers.load_lending_club_dataset()
a.describe(include='all').transpose()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
sex,4966,2,Male,4008,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,4966.0,NaN,NaN,NaN,34.335884,11.667358,18.0,25.0,31.0,42.0,80.0
juv_misd_count,4966.0,NaN,NaN,NaN,0.103504,0.531543,0.0,0.0,0.0,0.0,13.0
priors_count,4966.0,NaN,NaN,NaN,3.552356,4.950223,0.0,0.0,2.0,5.0,38.0
twoyearrecid,4966.0,NaN,NaN,NaN,0.5,0.50005,0.0,0.0,0.5,1.0,1.0
age_cat,4966,3,25-45,2857,NaN,NaN,NaN,NaN,NaN,NaN,NaN
race,4966,2,African-American,3004,NaN,NaN,NaN,NaN,NaN,NaN,NaN
c_charge_degree,4966,2,F,3248,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
from

{'compas-recidivism': {'sklearn': {'accuracy': 0.6197183098591549,
   'cfs': {'gaussian':       sex   age  juv_misd_count  priors_count        age_cat  \
    0  Female  19.0             0.0          10.0  Greaterthan45
    0    Male  19.0             0.0          10.0  Greaterthan45
    0  Female  50.0             0.0          10.0  Greaterthan45
    0  Female  45.0             0.0          10.0  Greaterthan45

                   race c_charge_degree  twoyearrecid
    0  African-American               F             0
    0         Caucasian               F             0
    0         Caucasian               F             0
    0         Caucasian               F             0  ,
    'random':       sex   age  juv_misd_count  priors_count        age_cat  \
    0  Female  53.0             0.0          10.0  Greaterthan45
    0    Male  49.0             0.0          11.0  Greaterthan45
    0  Female  19.0             0.0           0.0  Greaterthan45
    0    Male  19.0             0.0           0.0  Greaterthan45

                   race c_charge_degree  twoyearrecid
    0  African-American               F             0
    0         Caucasian               F             0
    0  African-American               F             0
    0  African-American               M             0  ,
    'spherical':       sex   age  juv_misd_count  priors_count        age_cat  \
    0  Female  19.0             0.0           0.0  Greaterthan45
    0    Male  19.0             0.0           0.0  Greaterthan45
    0  Female  19.0             0.0           0.0  Greaterthan45
    0  Female  19.0             0.0           0.0     Lessthan25

                   race c_charge_degree  twoyearrecid
    0  African-American               F             0
    0         Caucasian               F             0
    0         Caucasian               F             0
    0         Caucasian               F             0  },
   'input_instance': {'gaussian':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'random':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'spherical':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  },
   'time': {'gaussian': 15.71050214767456,
    'random': 59.52560997009277,
    'spherical': 201.18085503578186},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['age_cat', 'c_charge_degree', 'race', 'sex'], dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.5,
   'cfs': {'gaussian':       sex   age  juv_misd_count  priors_count        age_cat  \
    0  Female  49.6             0.0           0.0  Greaterthan45
    1  Female  78.0             0.0           0.0     Lessthan25
    2    Male  65.9             0.0           3.6  Greaterthan45
    3    Male  78.0            13.0           9.7  Greaterthan45

                   race c_charge_degree  twoyearrecid
    0  African-American               F         0.405
    1  African-American               F         0.340
    2  African-American               F         0.444
    3  African-American               F         0.445  ,
    'random':       sex   age  juv_misd_count  priors_count        age_cat  \
    0  Female  49.2             0.0           0.0  Greaterthan45
    1  Female  78.0             0.0           0.0     Lessthan25
    2    Male  65.9             0.0           3.7  Greaterthan45
    3    Male  78.0            13.0           9.7  Greaterthan45

                   race c_charge_degree  twoyearrecid
    0  African-American               F         0.406
    1  African-American               F         0.340
    2  African-American               F         0.444
    3  African-American               F         0.445  ,
    'spherical':       sex   age  juv_misd_count  priors_count        age_cat  \
    0  Female  49.4             0.0           0.0  Greaterthan45
    1  Female  78.0             0.0           0.0     Lessthan25
    2    Male  65.9             0.0           3.6  Greaterthan45
    3    Male  78.0            13.0          10.0  Greaterthan45

                   race c_charge_degree  twoyearrecid
    0  African-American               F         0.405
    1  African-American               F         0.340
    2  African-American               F         0.444
    3  African-American               F         0.447  },
   'input_instance': {'gaussian':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'random':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'spherical':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  },
   'time': {'gaussian': 49.472147941589355,
    'random': 131.80757880210876,
    'spherical': 64.41833806037903},
   'state_dict': OrderedDict([('0.weight',
                 tensor([[ 0.1509, -0.1866, -0.1786,  0.0358,  0.0144,  0.1202, -0.0672, -0.1954,
                           0.0626, -0.0888, -0.0147, -0.1858],
                         [ 0.3402,  0.1429, -0.2077, -0.0682, -0.2199, -0.1919,  0.1668, -0.1361,
                           0.3169, -0.0034,  0.1870,  0.1498],
                         [ 0.2507,  0.0591, -0.0500,  0.0175, -0.2314,  0.0348,  0.0374, -0.3053,
                          -0.1123,  0.2175,  0.2825, -0.0646],
                         [ 0.2462, -0.0503, -0.6126,  0.0376, -0.2659, -0.0599,  0.1436, -0.0105,
                           0.0152, -0.1115,  0.0245,  0.1025],
                         [-0.1795, -0.2624,  0.0683, -0.2397, -0.2933,  0.1259, -0.3305,  0.1976,
                           0.0592,  0.0109, -0.4571,  0.0066],
                         [-0.1407, -0.3568, -0.6235, -0.1010, -0.1742,  0.0464,  0.0323,  0.2604,
                          -0.1758, -0.0655, -0.0193, -0.0661],
                         [-0.0488, -0.2643, -0.4306, -0.3584,  0.0769,  0.1414, -0.0634, -0.0497,
                          -0.1684,  0.1027,  0.2177, -0.0137],
                         [ 0.2342, -0.1765, -0.6215, -0.0193, -0.1350,  0.1189,  0.0638, -0.0721,
                          -0.0153,  0.1869,  0.0147,  0.2517],
                         [ 0.1937,  0.0129,  0.2593,  0.0242, -0.2617, -0.0846,  0.0634, -0.1106,
                          -0.1288, -0.1856, -0.6867,  0.0231],
                         [-0.5649,  0.0994,  0.1746, -0.2905,  0.0849,  0.1002,  0.2283, -0.1333,
                           0.2224,  0.0256, -0.2739,  0.0362],
                         [-0.0886, -0.2856, -0.2661, -0.2713,  0.0031,  0.0847, -0.3082,  0.2421,
                           0.0238,  0.1156,  0.4045, -0.3985],
                         [-0.5254,  0.0504,  0.4328, -0.1288, -0.0996,  0.0807,  0.0256, -0.0543,
                           0.1300,  0.0508,  0.2547,  0.3873],
                         [-0.0430,  0.0983, -0.3417,  0.1936,  0.1568,  0.2736, -0.1489,  0.2122,
                          -0.1002, -0.0631, -0.0325,  0.0221],
                         [ 0.1024,  0.0906, -0.3569,  0.2930, -0.0570, -0.1163,  0.1588,  0.1475,
                           0.0076, -0.0715, -0.2848,  0.0913],
                         [-0.0987, -0.3929,  0.4556,  0.1217,  0.2221, -0.0724,  0.1679,  0.0197,
                           0.2291,  0.3009,  0.0131, -0.0457],
                         [ 0.2293, -0.2423, -0.2179,  0.0713, -0.1168,  0.0707,  0.1601,  0.1538,
                           0.1195,  0.2343, -0.0939,  0.0029],
                         [-0.2269, -0.0175,  0.5078,  0.3036, -0.1128, -0.0555,  0.0512,  0.0369,
                           0.3936,  0.1161, -0.1279,  0.3844],
                         [ 0.0449, -0.0794, -0.6439,  0.1335,  0.1344, -0.1209,  0.1330, -0.0937,
                           0.1824,  0.0068,  0.2312, -0.0162],
                         [ 0.1365, -0.2620, -0.6042,  0.3433, -0.1183, -0.0801, -0.0959,  0.0389,
                          -0.0975, -0.2073,  0.2938,  0.2781],
                         [ 0.2525,  0.1657,  0.1735,  0.2531,  0.0858, -0.0493, -0.3255,  0.0906,
                           0.1981, -0.0170, -0.1902, -0.2319]])),
                ('0.bias',
                 tensor([-0.2863,  0.1287,  0.0202,  0.2076,  0.0149,  0.1592, -0.1136,  0.0932,
                          0.0386,  0.1024, -0.1858,  0.0658,  0.0180, -0.0850,  0.0704, -0.0695,
                          0.3644,  0.0163, -0.0495,  0.2443])),
                ('2.weight',
                 tensor([[ 0.0347, -0.1768,  0.1201, -0.1888,  0.2739, -0.1727, -0.4287, -0.1854,
                          -0.3476,  0.3801, -0.3379,  0.4120, -0.1777, -0.1480,  0.2500, -0.1444,
                           0.2934, -0.3790, -0.3165, -0.1443]])),
                ('2.bias', tensor([-0.0093]))]),
   'model': Sequential(
     (0): Linear(in_features=12, out_features=20, bias=True)
     (1): ReLU()
     (2): Linear(in_features=20, out_features=1, bias=True)
     (3): Sigmoid()
   )},
  'TF2': {'accuracy': 0.696177065372467,
   'cfs': {'gaussian':     sex   age  juv_misd_count  priors_count     age_cat       race  \
    0  Male  48.7             0.0           3.6  Lessthan25  Caucasian
    1  Male  38.2             0.0          11.4  Lessthan25  Caucasian
    2  Male  58.2             0.0           9.9  Lessthan25  Caucasian
    3  Male  78.0             0.0          12.2  Lessthan25  Caucasian

      c_charge_degree  twoyearrecid
    0               F         0.263
    1               F         0.282
    2               F         0.249
    3               F         0.232  ,
    'random':     sex   age  juv_misd_count  priors_count     age_cat       race  \
    0  Male  49.1             0.0           3.4  Lessthan25  Caucasian
    1  Male  38.6             0.0          11.2  Lessthan25  Caucasian
    2  Male  58.5             0.0           9.7  Lessthan25  Caucasian
    3  Male  78.0             0.0          11.7  Lessthan25  Caucasian

      c_charge_degree  twoyearrecid
    0               F         0.263
    1               F         0.281
    2               F         0.248
    3               F         0.233  ,
    'spherical':     sex   age  juv_misd_count  priors_count     age_cat       race  \
    0  Male  49.1             0.0           3.4  Lessthan25  Caucasian
    1  Male  38.6             0.0          11.2  Lessthan25  Caucasian
    2  Male  58.5             0.0           9.7  Lessthan25  Caucasian
    3  Male  78.0             0.0          11.7  Lessthan25  Caucasian

      c_charge_degree  twoyearrecid
    0               F         0.263
    1               F         0.281
    2               F         0.248
    3               F         0.233  },
   'input_instance': {'gaussian':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'random':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  ,
    'spherical':        sex   age  juv_misd_count  priors_count        age_cat  \
    3264  Male  49.0             0.0          10.0  Greaterthan45

                      race c_charge_degree
    3264  African-American               F  },
   'time': {'gaussian': 114.43774485588074,
    'random': 184.05386304855347,
    'spherical': 188.56855082511902},
   'model': <dice_ml_x.utils.neuralnetworks.TF2Model at 0x466055850>,
   'model_path': 'compas-recidivism_TF2_model'}},
 'adult-income': {'sklearn': {'accuracy': 0.818426103646833,
   'cfs': {'gaussian':    age      workclass  education marital_status    occupation   race gender  \
    0   50  Self-Employed  Bachelors        Married  White-Collar  White   Male
    0   50        Private  Bachelors        Married       Service  White   Male
    0   50        Private  Bachelors        Married   Blue-Collar  White   Male
    0   50        Private  Bachelors        Married  White-Collar  White   Male

       hours_per_week  income
    0              40       1
    0              40       1
    0              40       1
    0              40       1  ,
    'random':    age      workclass  education marital_status     occupation   race  gender  \
    0   50  Self-Employed  Bachelors        Married  Other/Unknown  White    Male
    0   50        Private      Assoc        Married   Professional  White    Male
    0   17     Government    Masters        Married   Professional  White    Male
    0   17     Government      Assoc        Married   White-Collar  White  Female

       hours_per_week  income
    0              40       1
    0              40       1
    0              40       1
    0               1       1  ,
    'spherical':    age   workclass  education marital_status    occupation   race  gender  \
    0   17  Government  Doctorate        Married  Professional  White    Male
    0   50  Government  Bachelors        Married  Professional  White    Male
    0   17     Private      Assoc        Married  White-Collar  White  Female

       hours_per_week  income
    0               1       1
    0              40       1
    0               1       1  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    24228   50  Other/Unknown  Some-college        Married  Other/Unknown  White

          gender  hours_per_week
    24228   Male              40  ,
    'random':        age      workclass     education marital_status     occupation   race  \
    24228   50  Other/Unknown  Some-college        Married  Other/Unknown  White

          gender  hours_per_week
    24228   Male              40  ,
    'spherical':        age      workclass     education marital_status     occupation   race  \
    24228   50  Other/Unknown  Some-college        Married  Other/Unknown  White

          gender  hours_per_week
    24228   Male              40  },
   'time': {'gaussian': 43.11811685562134,
    'random': 425.4585599899292,
    'spherical': 2427.8730478286743},
   'model': Pipeline(steps=[('preprocessor',
                    ColumnTransformer(transformers=[('cat',
                                                     Pipeline(steps=[('onehot',
                                                                      OneHotEncoder(handle_unknown='ignore'))]),
                                                     Index(['education', 'gender', 'marital_status', 'occupation', 'race',
          'workclass'],
         dtype='object'))])),
                   ('classifier', RandomForestClassifier())])},
  'PYT': {'accuracy': 0.7608445297504799,
   'cfs': {'gaussian':    age      workclass     education marital_status     occupation   race  \
    0   50        Private     Bachelors        Married  Other/Unknown  White
    1   33  Other/Unknown     Bachelors      Separated  Other/Unknown  White
    2   71        Private  Some-college        Married          Sales  White
    3   50  Other/Unknown  Some-college        Widowed  Other/Unknown  Other

      gender  hours_per_week  income
    0   Male              29   0.835
    1   Male              40   0.753
    2   Male              40   0.792
    3   Male              43   0.631  ,
    'random':    age      workclass     education marital_status     occupation   race  \
    0   50        Private     Bachelors        Married  Other/Unknown  White
    1   36  Other/Unknown     Bachelors      Separated  Other/Unknown  White
    2   70        Private  Some-college        Married          Sales  White
    3   49  Other/Unknown  Some-college        Widowed  Other/Unknown  Other

      gender  hours_per_week  income
    0   Male              28   0.834
    1   Male              41   0.750
    2   Male              40   0.792
    3   Male              43   0.631  ,
    'spherical':    age      workclass     education marital_status     occupation   race  \
    0   50        Private     Bachelors        Married  Other/Unknown  White
    1   40  Other/Unknown  Some-college      Separated  Other/Unknown  White
    2   72        Private  Some-college        Married          Sales  White
    3   51        Private  Some-college        Widowed  Other/Unknown  Other

      gender  hours_per_week  income
    0   Male              28   0.834
    1   Male              42   0.584
    2   Male              40   0.792
    3   Male              46   0.839  },
   'input_instance': {'gaussian':        age      workclass     education marital_status     occupation   race  \
    24228   50  Other/Unknown  Some-college        Married  Other/Unknown  White

          gender  hours_per_week
    24228   Male              40  ,
    'random':        age      workclass     education marital_status     occupation   race  \
    24228   50  Other/Unknown  Some-college        Married  Other/Unknown  White

          gender  hours_per_week
    24228   Male              40  ,
    'spherical':        age      workclass     education marital_status     occupation   race  \
    24228   50  Other/Unknown  Some-college        Married  Other/Unknown  White

          gender  hours_per_week
    24228   Male              40  },
   'time': {'gaussian': 95.81541132926941,
    'random': 200.36280393600464,
    'spherical': 69.65415287017822},
   'state_dict': OrderedDict([('0.weight',
                 tensor([[-3.7751e-01,  2.0033e-01,  1.8185e-01, -6.8077e-02, -1.2836e-01,
                           1.0124e-01, -3.8263e-01, -2.5194e-01,  4.4710e-01, -1.9687e-02,
                           5.3672e-01, -2.5419e-01,  3.4029e-01, -3.4193e-01,  1.6882e-01,
                           2.4136e-01,  3.7882e-01, -8.2144e-02,  1.4641e-01,  1.9435e-01,
                           6.5153e-02,  4.9854e-01, -9.3639e-03,  9.1499e-02,  1.1894e-02,
                          -1.4927e-01,  1.3686e-01,  2.4386e-01,  1.9967e-01],
                         [ 6.7277e-02,  1.6611e-01, -3.4678e-01,  1.0297e-02,  5.4087e-01,
                          -2.3607e-01,  1.7667e-01,  4.6595e-01,  1.9831e-01, -5.2488e-01,
                          -3.3501e-01,  2.0267e-01,  2.4433e-01, -2.0969e-01,  4.1419e-02,
                           4.0259e-02,  5.8779e-01, -2.5971e-01, -1.2977e-02, -1.2140e-01,
                           2.6124e-01, -2.8609e-01,  4.4401e-01, -1.4130e-01, -7.3436e-02,
                          -1.8995e-01, -2.6626e-01, -5.0446e-02,  2.6084e-01],
                         [-8.6922e-02,  3.9691e-01, -5.3316e-03,  3.5625e-01, -3.6535e-01,
                          -6.0421e-02,  1.7585e-01, -6.1684e-01, -3.7226e-01,  1.3245e-01,
                           1.2060e-01, -2.1572e-01,  1.4569e-01, -1.5422e-01,  3.5776e-01,
                          -1.0761e-01,  1.1624e-01,  2.6447e-01, -3.1173e-01,  4.3710e-01,

In [9]:
d = dice_ml_x.Data(dataframe=train_dataset, continuous_features=["age", "juv_misd_count", "priors_count"], outcome_name='twoyearrecid')
numerical = ["age", "juv_misd_count", "priors_count"]
categorical = x_train.columns.difference(numerical)

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

transformations = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical)])

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
clf = Pipeline(steps=[('preprocessor', transformations),
                      ('classifier', RandomForestClassifier())])
model = clf.fit(x_train, y_train)

In [13]:
from sklearn.metrics import accuracy_score

predictions = model.predict(x_test)
accuracy = accuracy_score(y_test, predictions) * 100
print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 61.97%

In [38]:
# Using sklearn backend
m = dice_ml_x.Model(model=model, backend="sklearn")
# Using method=random for generating CFs
exp = dice_ml_x.DiceX(d, m, method="genetic")

In [39]:
cat_features = {}
for col in categorical:
    if col in df.columns:
        cat_features[col] = df[col].unique().tolist()
cat_features

{'age_cat': ['25-45', 'Lessthan25', 'Greaterthan45'],
 'c_charge_degree': ['F', 'M'],
 'race': ['African-American', 'Caucasian'],
 'sex': ['Male', 'Female']}

In [40]:
gaussian_kwargs = {
    'continuous_features': numerical,
    'categorical_features': cat_features,
    'std_dev': 0.3
}

random_kwargs = {
    'continuous_features': numerical,
    'categorical_features': cat_features,
    'feature_ranges': exp.data_interface.get_features_range_float()[1]
}

spherical_kwargs = {
    'continuous_features': numerical,
    'categorical_features': cat_features,
    'feature_ranges': exp.data_interface.get_features_range_float()[1]
}

e1 = exp.generate_counterfactuals(x_test[0:1], total_CFs=5, perturbation_method="gaussian", desired_class="opposite", **gaussian_kwargs)
e1.visualize_as_dataframe(show_only_changes=True)

100%|██████████| 1/1 [10:51<00:00, 651.37s/it]

Query instance (original outcome : 1)

,sex,age,juv_misd_count,priors_count,age_cat,race,c_charge_degree,twoyearrecid
0,Male,38.0,5.0,8.0,25-45,African-American,M,1

Diverse Counterfactual set (new outcome: 0)

,sex,age,juv_misd_count,priors_count,age_cat,race,c_charge_degree,twoyearrecid
0,-,40.0,0.0,-,Greaterthan45,-,-,0

In [41]:
import matplotlib.pyplot as plt

def plot_loss_metrics(loss_metrics):
    """Plots loss metrics over iterations or samples."""
    # Extract metrics
    proximity_loss = loss_metrics["proximity_loss"]
    sparsity_loss = loss_metrics["sparsity_loss"]
    robustness_loss = loss_metrics["robustness_loss"]
    yloss = loss_metrics["y_loss"]
    total_loss = loss_metrics["total_loss"]

    # Create a figure
    plt.figure(figsize=(10, 6))

    # Plot proximity loss
    plt.plot(proximity_loss, label="Proximity Loss", marker='o')

    # Plot sparsity loss
    plt.plot(sparsity_loss, label="Sparsity Loss", marker='s')

    # Plot robustness loss
    plt.plot(robustness_loss, label="Robustness Loss", marker='x')

    # Plot yloss
    plt.plot(yloss, label="Y Loss", marker='^')

    plt.plot(total_loss, label="Total Loss", marker='v')

    # Customize plot
    plt.title("Loss Metrics")
    plt.xlabel("Index (Iterations)")
    plt.ylabel("Loss Value")
    plt.legend()
    plt.grid()

    # Show plot
    plt.show()

plot_loss_metrics(exp.loss_history)

AttributeError: 'DiceGenetic' object has no attribute 'loss_history'